-- AlterTable
ALTER TABLE `user` ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true,
    MODIFY `role` ENUM('HR', 'INTERVIEWER', 'MANAGEMENT', 'HIRING_MANAGER', 'IT_ADMIN', 'LEADERSHIP_MANAGEMENT') NOT NULL;

-- AlterTable
ALTER TABLE `vacancy` ADD COLUMN `preferredSkills` VARCHAR(191) NULL,
    ADD COLUMN `requirements` VARCHAR(191) NULL;
